### ISSUE TITLE
[Suggestion] Reverse Switch Target

### ISSUE THREAD

**Issue by MrHydralisk** [TheDeadSnake/LC-Touchscreen#12]
When hold button like Shift and pressing "Switch target" key, then it will scroll through targets in reverse order. Would be very useful, when have big party of people or a lot of Radar Boosters.
Key 2 > 3 > 4 > 1
Shift+Key 2 > 1 > 4 > 3

**Comment by TheDeadSnake** [comment]
Mh..
In v1.0.7 I will add in two new config options:
 \> Another optional keybind
 \> A boolean option
So that you can either define a new keybind all together for reverse order e.g. (e.g. Q,E or Arrow Left,Arrow Right, ...) or just toggle the normal quick switch to reverse with the new keybind (e.g. Shift).

**Comment by TheDeadSnake** [comment]
v1.0.7:
* Added additional optional key bind
* Added config option to decide behaviour of the new optional key bind
 \> True: When key bind is pressed, the quick switch will go in the reverse order
 \> False: When key bind is pressed, the previous radar target will be selected
