### ISSUE TITLE
Missing folder on thunderstore

### ISSUE THREAD

**Issue by FortniteGamer42069** [TheDeadSnake/LC-Touchscreen#5]
When manually donwloadig the files, the png and dll arent in the "TheDeadSnake-Touchscreen" folder and causes the HoverIcon not do load

**Comment by TheDeadSnake** [comment]
If you manually install the plugin, you have to make sure the folder name matches what Thunderstore would call the folder.
I can't implement another way, as if you install it manually you could in theory call the folder whatever you want and I would need to check all plugin resources in order to locate it, 
Furthermore in v1.0.4 there will be support for more / custom icons which will make locating the file impossible.
(Unless there is a path value that points to the plugin (.dll location) directory directly)
