### ISSUE TITLE
Where to place icons in folder

### ISSUE THREAD

**Issue by wadawan929** [TheDeadSnake/LC-Touchscreen#9]
where should i place my icons in my folder for lethal company?
eg: 
- HoverIcon.png
- DotIcon.png
- CrossIcon.png

**Comment by TheDeadSnake** [comment]
If you installed the mod normally (Through Thunderstore) the default icons should already be at the correct location and you just need to edit the config\* file in order to switch between them.
If you want to use your own icons or you installed the mod manually and did not call the folder "TheDeadSnake-Touchscreen", you can either override the default ones or just edit the config\* file and set the variable\*\* to a full path to the file somewhere on your system.

\*) The config "me.pm.TheDeadSnake.cfg" is located inside your "BepInEx/config/" folder.
\*\*) The image variable is under the header "UI" and is called "PointerIcon" examples can be found in the variable description above.

**Comment by wadawan929** [comment]
so if i installed my mods manually, should the icons be inside a folder called 'TheDeadSnake-Touchscreen' inside of my main bepinex folder?

**Comment by wadawan929** [comment]
> TheDeadSnake-Touchscreen

ok i fixed the issue, thanks for the support, i have been manually installing my mods lolol
